
allout:	OUTPUT/ib.out OUTPUT/im.out OUTPUT/it.out OUTPUT/pb.out OUTPUT/pm.out OUTPUT/pt.out OUTPUT/sb.out OUTPUT/sm.out	OUTPUT/st.out	
	echo "end running scripts"

OUTPUT/ib.out:	ib.py
	./ib.py 

OUTPUT/im.out:	im.py
	./im.py 

OUTPUT/it.out:	it.py
	./it.py 

OUTPUT/pb.out:	pb.py
	./pb.py 

OUTPUT/pm.out:	pm.py
	./pm.py 

OUTPUT/pt.out:	pt.py
	./pt.py

OUTPUT/sb.out:	sb.py
	./sb.py 

OUTPUT/sm.out:	sm.py
	./sm.py 

OUTPUT/st.out:	st.py
	./st.py 
